### ISSUE TITLE
[Core] Engine can scan 5 tools with default config.

### ISSUE THREAD

**Issue by katopz** [rabbotio/eyes-core#1]
## Expected
> Can scan and save output with below tools via Ubuntu 16.04.1 x64  
- [X] `nmap`
- [X] `w3af`
- ~~[ ] `wpscan`~~
- ~~[ ] `wappalyzer`~~
- [X] `wweb`
- [x] Provide how to scan each tool via `README.md`

**Comment by NiponChi** [comment]
cancelled two tools (wpscan and wappalyzer), due to license and irrelevant to security
Images have been uploaded to https://hub.docker.com/u/rabbotio/

See:
https://github.com/rabbotio/eyes-core/blob/master/README.md
https://github.com/rabbotio/eyes-core/blob/master/images/utils/w3af/README.md
