### ISSUE TITLE
[Core] Add wapiti support as docker container

### ISSUE THREAD

**Issue by katopz** [rabbotio/eyes-core#2]
See step 4 at https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-on-ubuntu-14-04

**Comment by NiponChi** [comment]
docker run --rm -ti -v $HOME/share:/tmp/share rabbotio/wapiti http://example.com -n 1 -o /tmp/share/output

**Comment by katopz** [comment]
wapiti seem to outdate
